# Generated by Django 4.2.10 on 2024-02-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animeSuki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_anime',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('upload', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
