# Generated by Django 4.2.10 on 2024-02-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animeSuki', '0003_add_manga'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_anime',
            name='details',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='add_anime',
            name='rating',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
