# Generated by Django 4.2.10 on 2024-02-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animeSuki', '0004_add_anime_details_add_anime_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_anime',
            name='upload',
            field=models.ImageField(upload_to=''),
        ),
    ]
