# Generated by Django 4.2.10 on 2024-02-21 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animeSuki', '0005_alter_add_anime_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_anime',
            name='upload',
        ),
    ]
