# Generated by Django 4.2.10 on 2024-02-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animeSuki', '0006_remove_add_anime_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_anime',
            name='image',
            field=models.ImageField(default=1, upload_to=None),
            preserve_default=False,
        ),
    ]
