# Generated by Django 4.2.10 on 2024-02-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animeSuki', '0008_alter_add_anime_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_manga',
            name='upload',
        ),
        migrations.AddField(
            model_name='add_manga',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
