# Generated by Django 4.2.10 on 2024-02-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animeSuki', '0009_remove_add_manga_upload_add_manga_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_manga',
            name='details',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='add_manga',
            name='rating',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
